### ISSUE TITLE
Support flipping images vertically.

### ISSUE THREAD

**Issue by mintyfresh** [tjhann/imagefmt#2]
One quirk of OpenGL and some other graphics APIs is that the (0, 0) is expected to be at the bottom left corner of the image, whereas most image formats place (0, 0) at the top left. This usually relates to how Y-axis coordinates are projected (with OpenGL placing Y:0 at the bottom of the screen).

A number of image libraries provide flags or functions to perform this flipping behaviour,
ie. stb_image provides:
```c++
stbi_set_flip_vertically_on_load(true);
```
Which indicates that subsequent images should be loaded with their Y-axes reversed.

Implementing this at application level can be tricky, since some image formats (BMP) are stored bottom-up, whereas others are stored top-down.

**Comment by ghost** [comment]
Not tricky, because imagefmt always places the top-left corner at the origin coordinates (0, 0) for this very reason. The writing functions also assume those coordinates. But I guess this could be added anyway since flipping is quite commonly needed when loading or saving images. It could just be a function.

I improved documentation.

**Comment by mintyfresh** [comment]
> It could just be a function.

One reason for preferring a flag over a function might be for the case of image formats that are stored with their Y-axis inverted, it would prevent performing redundant work when loading the content.

However, either option would be acceptable.

**Comment by ghost** [comment]
Yeah. The flag just requires a little bit more code in every decoder. Nothing complicated though because for at least all currently supported formats it's very easy to do on the fly. So I'm now leaning towards the flag :)

To be clear, the flipping is already done on the fly when needed (bmp, tga) so no extra work is done at all with any of the currently supported formats in case user wants Y-axis to point down.

**Comment by ghost** [comment]
I added functions to control vertical orientation with:
```
void set_yaxis_up_on_load(bool up)
void set_yaxis_up_on_save(bool up)
```
I didn't bother making it efficient for jpeg.
